name: redicli
base: core22
version: '1.0'
summary: A TUI for Redis
description: |
  RediCLI is a terminal-based UI for Redis, built with Go using tcell and tview.

grade: stable
confinement: strict

parts:
  redicli:
    plugin: go
    source: .
    build-packages:
      - golang

apps:
  redicli:
    command: bin/redicli
    plugs:
      - network
