name: redicli
version: '1.0'
summary: A CLI tool for Redis
description: |
  A terminal user interface for Redis with go-redis.

confinement: classic

parts:
  redicli:
    plugin: go
    source: .
    go-importpath: github.com/yourusername/redicli
    build-packages:
      - build-essential
      - golang
    stage-packages:
      - libc6
    override-build: |
      go mod download
      go build -o bin/redicli ./cmd/redicli

apps:
  redicli:
    command: bin/redicli
