name: Build and Publish RediCLI Snap

on:
  push:
    branches:
      - deployed
  pull_request:
    branches:
      - deployed

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    env:
      SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_TOKEN }}

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install Snapcraft
        uses: samuelmeuli/action-snapcraft@v3

      - name: Log in to Snap Store
        run: |
          echo "${{ secrets.SNAPCRAFT_TOKEN }}" > snapcraft_login
          export SNAPCRAFT_STORE_CREDENTIALS=$(cat snapcraft_login)
          snapcraft login

      - name: Install LXD (needed for Snapcraft build with LXD)
        run: sudo apt-get install -y lxd

      - name: Build Snap with LXD
        run: sg lxd -c 'snapcraft --use-lxd'

      - name: Publish Snap Package
        run: snapcraft upload --release=stable *.snap
