name: Build and Publish RediCLI Snap

on:
  push:
    branches:
      - deployed
  pull_request:
    branches:
      - deployed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code from your repository
      - uses: actions/checkout@v4

      # Step 2: Build the Snap package
      - uses: snapcore/action-build@v1
        id: build
        env:
          SNAPCRAFT_PROJECT_PATH: ./  # Path to your snapcraft.yaml file (root directory)

      # Step 3: Publish the Snap package to Snap Store
      - uses: snapcore/action-publish@v1
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.STORE_LOGIN }}  # Your Snapcraft login token
        with:
          snap: ${{ steps.build.outputs.snap }}  # The built snap file from the build step
          release: edge  # You can change this to 'stable' or 'beta' based on your requirements
