name: Build and Publish Snap

on:
  push:
    branches:
      - deployed
  pull_request:
    branches:
      - deployed

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Snapcraft
        run: |
          sudo apt update
          sudo apt install -y snapd
          sudo snap install snapcraft --classic

      - name: Authenticate with Snap Store
        run: |
          echo "${{ secrets.SNAPCRAFT_TOKEN }}" > snapcraft_login
          export SNAPCRAFT_STORE_CREDENTIALS=$(cat snapcraft_login)
          snapcraft login

      - name: Build Snap Package
        run: snapcraft --destructive-mode

      - name: Publish Snap Package
        run: snapcraft upload --release=stable *.snap
